# Steps of register form
START_REGISTERING, JOIN_CHANNEL, FOLLOW_TWITTER, GET_TWITTER_USERNAME, CONFIRM_TWITTER_USERNAME, GET_EMAIL, CONFIRM_EMAIL, GET_WALLET, CONFIRM_WALLET, DONE = range(
    10)

GET_S2A_ALL = range(1)
GET_S2A_NR = range(1)
GET_S2A_R = range(1)
GET_TXID = range(1)

SELECT_INFORMATION, EDIT_TWITTER, EDIT_EMAIL, EDIT_WALLET = range(4)